### ISSUE TITLE
Allow using custom SQLite3Provider

### ISSUE THREAD

**Issue by altso** [neosmart/SqliteCache#17]
I have a need to use a custom SQLite3Provider which could be set using `SQLitePCL.raw.SetProvider()` method. It's a supported scenario and documented [here](https://github.com/ericsink/SQLitePCL.raw#a-trio-of-packages).

Unfortunately `SqliteCache` references `SQLitePCLRaw.bundle_green` and makes a call to `SQLitePCL.Batteries.Init()` which makes it impossible to use a custom provider.

https://github.com/neosmart/AspSqliteCache/blob/9436df9361b0dc95eef01426970fd82a9c20cb19/SqliteCache/SqliteCache.cs#L30-L33

Do you think it's possible to have a reference to `SQLitePCLRaw.core` instead of `SQLitePCLRaw.bundle_green` and make it user's responsibility to call `SQLitePCL.Batteries.Init()` or whatever method they decide to use?

I can send a PR if you are ok with such a change.

**Comment by mqudsi** [comment]
This is actually already the plan for v7.0 

Let me get out the last non-preview v6.x release and I'll push out a v7.0 beta.

**Comment by mqudsi** [comment]
I have just published `7.0.0-preview1` that no longer relies on `SQLitePCLRaw.bundle_green`. Can you please give it a try?

**Comment by mqudsi** [comment]
https://github.com/neosmart/AspSqliteCache/releases/tag/7.0.0-preview1

**Comment by altso** [comment]
Thank you so much.
