### ISSUE TITLE
I want to secure sqlite db with username and password. Is there any option available to do that? When would be the stable version of 7 available?

### ISSUE THREAD

**Issue by taruntomar** [neosmart/SqliteCache#18]

**Comment by mqudsi** [comment]
7.0 was released in September of 2023 and is available on Nuget. I just released 8.0 (7.0 was compatible with ASP.NET Core 8.0).

You should use filesystem permissions to make the database only readable to the account associated with the web application, there is no option to use a username and password in standard SQLite.
