### ISSUE TITLE
Dependency on ISQLite3Provider?

### ISSUE THREAD

**Issue by cosmoKenney** [neosmart/SqliteCache#20]
I am working on .net 8.0  web api project. Trying to setup the cache but ran into a dependency that is not documented in the readme...
![image](https://github.com/neosmart/SqliteCache/assets/3654426/0cdaf307-a860-467a-a6af-8788de1e72bb)
I installed NeoSmart.Caching.Sqlite. Should I continue to use the .net standard version (NeoSmart.Caching.Sqlite.AspNetCore)?

**Comment by cosmoKenney** [comment]
> That’s documented in the readme unless I’m missing something, but yes, for web projects use the second package.

@mqudsi , sorry, but I don't see any code in the readme that describes how to use the AddSqliteCache that takes two parameters. 
I just reread the "Installation" section, however. And it is obvious that I should have installed NeoSmart.Caching.Sqlite.AspNetCore. I did that and I am back in business. Thanks for the fast reply, BTW.

**Comment by mqudsi** [comment]
Ah, sorry, what I meant is that the documentation shows you need to use the `AspNetCore` package. I'll try to update the docs for the top-level version when I can.
