### ISSUE TITLE
Error using SqliteCache with FusionCache

### ISSUE THREAD

**Issue by dperez83** [neosmart/SqliteCache#22]
Hello,

I get the exception bellow while using Sqlite cache with FusionCache like this https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/DiskCache.md

The error occurs with version 7.0 and higher. With 6.10 it works fine.

It occurs in the line 
```
 .WithDistributedCache(
        new SqliteCache(new SqliteCacheOptions { CachePath = "CACHE PATH" })
    )
```

```
System.Exception: 'You need to call SQLitePCL.raw.SetProvider(). If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().'
````

Can you please verify?

Thank you

**Comment by dperez83** [comment]
Turns out I was using the wrong Nuget package. I was using the NeoSmart.Caching.Sqlite instead of the NeoSmart.Caching.Sqlite.AspNetCore.

**Comment by mqudsi** [comment]
Yup, glad you got it. Let me know if you think the docs could be updated in a specific way to make that clearer.
